### ISSUE TITLE
Orthogonal surfaces

### ISSUE THREAD

**Issue by shyuep** [henniggroup/MPInterfaces#1]
Hi there,

Great work on this package.

I was browsing and I saw that you mentioned that ASE supports orthogonal Slabs but pymatgen doesn't. I should let you know that the most recent pymatgen already supports this. There are two options:

1. Using the max_normal_search option, which will look for c lattice vectors that preserve symmetry and are as normal as possible to the a and b lattice vectors. Orthogonality is not guaranteed, but for many typical high symmetry structures, this works well.

2. Slab now has a get_orthogonal_c_slab() method (see https://github.com/materialsproject/pymatgen/commit/1cf37e77971fc1c8c9c7a1bc6067e4b86260cbf5). This returns a Slab that has the c vector to be exactly orthogonal to the a and b surface vectors. Note that such forcing of orthogonality changes the Slab symmetry, though if your vacuum size is large enough, it usually isn't a problem.

**Comment by matk86** [comment]
Hi Shyuep,
Thats great news ! Now we can get rid of that ase dependency.
We will test it and possibly update soon.
thanks
-Kiran Mathew
