### ISSUE TITLE
KeyError:symbols

### ISSUE THREAD

**Issue by KatherineJY** [henniggroup/MPInterfaces#18]
I try to run the example mentioned in doc : 'mpint -i naf.yaml -t bulk_calibrate run', but get error(KeyError:symbols) in pytmatgen/io/vasp/input.py at line 1742.
Before enter the construction MPINTVaspInputSet(name, self.incar, self.poscar, self.kpoints, self.potcar,self.qadapter, vis_logger=self.logger,euse_path=self.reuse_paths, test=self.test)(in calibrate.py at line 833) , self.potcar has key "symbols". But when self.potcar is passed to this construction MPINTVaspInputSet as argument, it changes. There is no key named "symbols" or "functional", which is needed to generate a potcar.

I'm very confused about this error and I'm looking forward to your answer. Thanks!

**Comment by joshgabriel** [comment]
Thanks for posting the issue! It should be resolved now.
