### ISSUE TITLE
calibrate.py creates folder names with spaces

### ISSUE THREAD

**Issue by marcoesters** [henniggroup/MPInterfaces#3]
When run_cal is called with is_matrix=false, the folder names extracted from the first line of the POSCAR file contain spaces which not every cluster can handle.

Proposed change: change line 282 from
return val.comment
to
return val.comment.replace(' ','_').replace('\t','_')
to replaces spaces with underscores.

**Comment by matk86** [comment]
thanks.
merged your pull request
