### ISSUE TITLE
variable not defined

### ISSUE THREAD

**Issue by matk86** [henniggroup/MPInterfaces#9]
https://github.com/henniggroup/MPInterfaces/blob/fd9931e86166ef74d6b39b6c4ad93d291408ae9b/mpinterfaces/twod_materials/magnetism/startup.py#L57

**Comment by matk86** [comment]
Thanks
@joshgabriel @ashtonmv not completely unrelated to this,  could you guys refactor the twod_materials subpackage and reduce the code duplications?

**Comment by ashtonmv** [comment]
Yeah, good idea. I am working on a branch right now to merge all the utils functions into mpinterfaces.utils. I think that is where most of the code overlap is happening...

**Comment by matk86** [comment]
Great! 👍
